name: Create issues from todos

on:
    workflow_dispatch:
        inputs:
            importAll:
                default: false
                required: false
                type: boolean
                description: Create issues for all todos, not just from the last commit [ONLY USE THIS IF YOU KNOW WHAT YOU ARE DOING]
    push:
        branches: # do not set multiple branches, todos might be added and then get referenced by themselves in case of a merge
            - nightly

jobs:
    todos:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Create issues from todos
              uses: derjuulsn/todo-issue@3c0b9bf8277455978dc4907155f430925e8607df
              with:
                  keywords: |
                      todo
                      @todo
                      fixme
                      bug
                      xxx
                      hack
                      optimize
                      optimise
                      review
                      refractor
                  caseSensitive: false
                  excludePattern: "^(node_modules/)"
              env:
                  GITHUB_TOKEN: ${{ secrets.ROBOT_TOKEN }}
